apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3000        # internal Kubernetes port
      targetPort: 3000  # container port
      nodePort: 30001   # access from Minikube
